# !/usr/bin/env python3
# -*- coding:utf-8 -*-
"""Unit tests for the generated protobuf module agentuniverse_service_pb2.

The module is generated by the protocol buffer compiler and defines the
message classes used by the agentuniverse gRPC service: AgentServiceRequest,
AgentServiceResponse and AgentResultRequest.  The tests below cover the
deterministic, pure behaviors of these classes: field defaults, assignment
round-trips and protobuf serialization/deserialization.
"""

import pytest

from agentuniverse.agent_serve.web.rpc.grpc import agentuniverse_service_pb2 as pb2


class TestAgentServiceRequest:
    """Tests for the AgentServiceRequest message."""

    def test_defaults_are_empty(self):
        request = pb2.AgentServiceRequest()
        assert request.service_id == ""
        assert request.params == ""
        assert request.saved is False

    def test_field_assignment_round_trip(self):
        request = pb2.AgentServiceRequest(
            service_id="svc-1", params='{"k": "v"}', saved=True
        )
        assert request.service_id == "svc-1"
        assert request.params == '{"k": "v"}'
        assert request.saved is True

    def test_serialize_and_parse_round_trip(self):
        request = pb2.AgentServiceRequest(
            service_id="svc-2", params="payload", saved=False
        )
        data = request.SerializeToString()
        parsed = pb2.AgentServiceRequest.FromString(data)
        assert parsed == request
        assert parsed.service_id == "svc-2"
        assert parsed.params == "payload"
        assert parsed.saved is False


class TestAgentServiceResponse:
    """Tests for the AgentServiceResponse message."""

    def test_constructor_sets_fields(self):
        response = pb2.AgentServiceResponse(
            message="done", success=True, request_id="req-1", result="{}"
        )
        assert response.message == "done"
        assert response.success is True
        assert response.request_id == "req-1"
        assert response.result == "{}"

    def test_serialize_and_parse_round_trip(self):
        response = pb2.AgentServiceResponse(
            message="ok", success=False, request_id="req-2", result="[]"
        )
        parsed = pb2.AgentServiceResponse.FromString(response.SerializeToString())
        assert parsed == response

    def test_equality_of_equivalent_messages(self):
        first = pb2.AgentServiceResponse(message="m", success=True)
        second = pb2.AgentServiceResponse(message="m", success=True)
        assert first == second


class TestAgentResultRequest:
    """Tests for the AgentResultRequest message."""

    def test_default_request_id_is_empty(self):
        request = pb2.AgentResultRequest()
        assert request.request_id == ""

    def test_field_assignment_round_trip(self):
        request = pb2.AgentResultRequest(request_id="rid-42")
        assert request.request_id == "rid-42"

    def test_serialize_and_parse_round_trip(self):
        request = pb2.AgentResultRequest(request_id="rid-43")
        parsed = pb2.AgentResultRequest.FromString(request.SerializeToString())
        assert parsed == request
        assert parsed.request_id == "rid-43"


def test_descriptor_defines_three_message_types():
    """The module descriptor should expose the three service messages."""
    message_names = {msg.name for msg in pb2.DESCRIPTOR.message_types_by_name.values()}
    assert "AgentServiceRequest" in message_names
    assert "AgentServiceResponse" in message_names
    assert "AgentResultRequest" in message_names


if __name__ == "__main__":
    pytest.main([__file__, "-s"])
